# SERVER CONFIG
dev-server-config:
  # EXPOSED PORTS
  port: 8081

  # CORS ALLOW LIST
  allow-list:
    - "*"

  # ALLOWED SERVER REQUEST METHODS
  method-list:
    - GET
    - POST 
    - PUT

  # REQUIRES AUTH TOKEN
  requires-auth: false

# LOGGING CONFIG
server-log-config:

  # LIST OF FILE HANDLERS
  log-file-handlers:
    - file-path:  LOGS/devlog.txt
      level:      INFO
    
    - file-path:  LOGS/prod.txt
      level:      INFO